---

services:
  mariadb:
    image: mariadb:latest
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}

  phpmyadmin:
    image: phpmyadmin
    volumes:
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
    ports:
      - ${PHPMYADMIN_PORT}:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=${MARIADB_ROOT_PASSWORD}

  postgres:
    image: postgres:latest
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_HOST_AUTH_METHOD=md5
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  pgadmin4:
    image: dpage/pgadmin4
    volumes:
      - ./pgadmin4/servers.json:/pgadmin4/servers.json
      - pgadmin4:/var/lib/pgadmin
    ports:
      - ${PGADMIN_PORT}:80
    environment:
      - PGADMIN_LISTEN_PORT=80
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASS}
      - PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True
      - PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=10

volumes:
  mariadb:
  pgdata:
  pgadmin4:
